### ISSUE TITLE
Remove cloud http worker from docs

### ISSUE THREAD

**Issue by urbanisierung** [camunda-cloud/camunda-cloud-docs#29]
- [ ] Update [Quick start](https://docs.cloud.camunda.io/docs/quick-start): connect own worker
- [ ] Remove [Embedded HTTP Worker](https://docs.cloud.camunda.io/docs/http-worker)
- [ ] Update [Tutorial: Test Drive Camunda Cloud](https://github.com/jwulf/camunda-cloud-test-drive)

**Comment by ultraschuppi** [comment]
paging @jwulf - seems like https://github.com/jwulf/camunda-cloud-test-drive is still using the no-longer-available camunda-cloud-http-worker
